version: '3'
volumes:
  gem_data:
    driver: local
  db_data:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      BUNDLE_JOBS: 4
      BUNDLE_PATH: /usr/local/bundle
    ports:
      - '8888:8888'
    volumes:
      - .:/usr/src/app
      - gem_data:/usr/local/bundle
    command:
      bin/start_server.sh
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql